name: network_layer
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^0.13.5
  http_interceptor: ^1.0.2
  data_connection_checker_nulls: ^0.0.2
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  mocktail: ^1.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
